name: Delete dev documentation

on:
  pull_request:
    types: [ closed ]


jobs:
  delete:
    uses: huggingface/doc-builder/.github/old_workflows/delete_doc_comment.yml@main
    with:
      pr_number: ${{ github.event.number }}
      package: diffusers
